import type { Metadata } from "next";
import "./globals.css";
import { Fira_Code, Pacifico, Raleway } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { TooltipProvider } from "@/components/ui/tooltip";
import { AppProvider } from "./context/AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const firaCode = Fira_Code({
  subsets: ["latin"],
  display: "swap",
});

const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway",
});

const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-pacifico",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${firaCode.className} ${raleway.variable} ${pacifico.variable} antialiased`}
      >
        <AppProvider>
          <ThemeProvider attribute="class" defaultTheme="dark">
            <TooltipProvider>
              {children}
            </TooltipProvider>
          </ThemeProvider>
        </AppProvider>
      </body>
    </html>
  );
}
