import type { Metadata } from "next";
import "./globals.css";
import { Fira_Code, Pacifico, Raleway } from "next/font/google";
import Layout from "./components/Layout";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const firaCode = Fira_Code({
  subsets: ["latin"],
  display: "swap",
});

const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway",
});

const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-pacifico",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const supabaseUrl = "https://qrpdfdgniphartwuyeqp.supabase.co";
  // const supabaseKey = process.env.SUPABASE_KEY;
  // const supabase = createClient(supabaseUrl, supabaseKey);

  return (
    <html lang="en" className="dark">
      <body
        className={cn(firaCode.className, raleway.variable, pacifico.variable)}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
